language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

# Get AAF-devel libs

env:
    - AAF_ROOT=AAF-devel

before_install:
    - mkdir AAF-devel
    - cd AAF-devel
    - wget http://sourceforge.net/projects/aaf/files/AAF-devel-libs/1.1.6/AAF-devel-libs-x86_64Linux-1.1.6.0.tar.gz
    - tar -xvf AAF-devel-libs-x86_64Linux-1.1.6.0.tar.gz
    - cd ..
    - sudo add-apt-repository -y ppa:mc3man/trusty-media
    - sudo apt-get update -qq
    - sudo apt-get install ffmpeg

# Install build requirements.
install: pip install cython

script:
    - make install
    - make test
